# Generated by Django 4.0.1 on 2023-05-23 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('rpds_app', '0002_customersignup'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerSignUp',
            new_name='CustomUser',
        ),
    ]
