# Generated by Django 4.0.1 on 2023-05-23 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rpds_app', '0003_rename_customersignup_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
