# Generated by Django 4.0.1 on 2023-05-24 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rpds_app', '0005_contact_created_at_contact_name_alter_contact_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='created_at',
        ),
    ]
