# Generated by Django 4.0.1 on 2023-05-24 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rpds_app', '0007_alter_contact_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='name',
        ),
    ]
