# Generated by Django 4.0.1 on 2023-05-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpds_app', '0009_contact_created_at_contact_name_alter_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.TextField(max_length=255),
        ),
    ]
